swagger: "2.0"
info:
    title: "Platform Admin API"
    description: "Docs for Platform Admin API"
    version: "1.0.0"
schemes:
    - "http"
host: dev.prodact.me
basePath: /api

produces:
    - "application/json"
consumes:
    - "application/json"

paths:
    courses:
        get:
            tags:
                - "Courses"
            summary: "Courses lists"
            parameters:
            responses:
                200:
                    description: "Successful operation or custom errors"
                    schema:
                        $ref: "#/definitions/ResponseModel"

    courses/{course}:
        get:
            tags:
                - "Courses"
            summary: "Login user"
            parameters:
              -   name: "course"
                  in: "path"
                  description: "course id"
                  required: true
            responses:
                200:
                    description: "Successful operation or custom errors"
                    schema:
                        $ref: "#/definitions/ResponseModel"

    lessons/{lesson}:
        get:
            tags:
                - "Lessons"
            summary: "Login user"
            parameters:
                -   name: "lesson"
                    in: "path"
                    description: "lesson id"
                    required: true
            responses:
                200:
                    description: "Successful operation or custom errors"
                    schema:
                        $ref: "#/definitions/ResponseModel"

    defalt responses:
        post:
            tags:
                - "default responses"
            responses:
                200:
                    description: "Successful operation"
                401:
                   description: "Unauthorized"
                403:
                   description: "Forbidden"
                404:
                   description: "Not found"
                422:
                   description: "Validation error"
                500:
                   description: "Internal server error"


definitions:

  ResponseModel:
    type: "object"
